site_name: Ballance Blender Plugin Manual
site_description: 'The user manual of Ballance Blender Plugin'
site_author: 'yyc12345'
site_url: 'https://yyc12345.github.io/BallanceBlenderHelper/'
copyright: 'Text is available under the <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a>.'

nav:
  - 「    」: 'index.md'
  - English:
    - 'Start': 'en/index.md'
    - 'Install Plugin': 'en/install-plugin.md'
    - 'Configure Plugin': 'en/configure-plugin.md'
    - 'Virtools Properties': 'en/virtools-properties.md'
    - 'Ballance Properties': 'en/ballance-properties.md'
    - 'Import and Export Virtools Document': 'en/import-export-virtools.md'
    - 'Group Operation': 'en/group-operations.md'
    - 'Legacy Alignment': 'en/legacy-align.md'
    - 'Naming Convention': 'en/naming-convention.md'
    - 'UV Mapping': 'en/uv-mapping.md'
    - 'Add Floor': 'en/bme-adder.md'
    - 'Add Rail': 'en/rail-adder.md'
    - 'Add Component': 'en/component-adder.md'
    - 'ZZQ Features': 'en/zzq-features.md'
    - 'Compile and Distribute Plugin': 'en/compile-distribute-plugin.md'
    - 'Report Issue': 'en/report-bugs.md'
    - 'Technical Information': 'en/tech-infos.md'
  - 简体中文:
    - '开始': 'zh-cn/index.md'
    - '安装插件': 'zh-cn/install-plugin.md'
    - '配置插件': 'zh-cn/configure-plugin.md'
    - 'Virtools属性': 'zh-cn/virtools-properties.md'
    - 'Ballance属性': 'zh-cn/ballance-properties.md'
    - '导入导出Virtools文档': 'zh-cn/import-export-virtools.md'
    - '按组操作': 'zh-cn/group-operations.md'
    - '传统对齐': 'zh-cn/legacy-align.md'
    - '命名规则': 'zh-cn/naming-convention.md'
    - 'UV贴图': 'zh-cn/uv-mapping.md'
    - '添加路面': 'zh-cn/bme-adder.md'
    - '添加钢轨': 'zh-cn/rail-adder.md'
    - '添加机关': 'zh-cn/component-adder.md'
    - 'ZZQ功能': 'zh-cn/zzq-features.md'
    - '编译与分发插件': 'zh-cn/compile-distribute-plugin.md'
    - '报告问题': 'zh-cn/report-bugs.md'
    - '技术信息': 'zh-cn/tech-infos.md'

theme:
  name: readthedocs
  locale: en
  include_homepage_in_sidebar: false

plugins: []

extra:
  alternate:
    - name: English
      link: /BallanceBlenderHelper/en/home
      lang: en
    - name: 简体中文
      link: /BallanceBlenderHelper/zh-cn/home
      lang: zh

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

