name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - ng

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ng
        uses: actions/checkout@v4
        with:
          ref: ng

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: docs/mkdocs.yml
          # GITHUB_DOMAIN: github.myenterprise.com
